name: Python

on: [push, pull_request]

jobs:
  ai4ts-compare:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: venv setup
        run: |
         python3.10 -m venv venv
         . venv/bin/activate
         echo PATH=$PATH >> $GITHUB_ENV
         echo VIRTUAL_ENV=$VIRTUAL_ENV >> $GITHUB_ENV
      - name: minimal install
        run: pip install -e .
      - name: ai4ts-compare
        run: ai4ts-compare -i test/arima.yaml -l 24 -f h --models arma auto-arma -o compare.pdf
      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compare.pdf
          path: compare.pdf
          if-no-files-found: error
